name: build

on:
  push

                
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
         - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: hannahtiffany3/liatrio-apprenticeship:latest
          #secrets: GIT_AUTH_TOKEN=${{ screts.GITHUB_TOKEN }}
  test:
    name: test
    needs: build
    runs-on: http://172.17.0.1:80
    steps:
      - name: run tests
        uses: liatrio/github-actions/apprentice-action@master
     

