name: build

on:
  push

                
jobs:
  build:
    name: build and run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        uses: docker/build-push-action@v5
        with:
          push: false 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/liatrio-apprenticeship:latest
      - name: Run and push
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: ${{ secrets.DOCKERHUB_USERNAME }}/liatrio-apprenticeship:latest
          docker_network: e2a6a2d200e1
  test:
    name: test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        uses: liatrio/github-actions/apprentice-action@master
     

