name: build

on:
  push

                
jobs:
  build:
    name: build and run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        uses: docker/build-push-action@v5
        with:
          push: false 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/liatrio-apprenticeship:latest
      - name: run
        run: docker run -d --publish 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/liatrio-apprenticeship:latest
      - name: push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/liatrio-apprenticeship:latest
      - name: test
        uses: liatrio/github-actions/apprentice-action@master
     

